# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats: []

# Optionally set the version of Python and requirements required to build your
# docs
python:
  version: 3.8
  install:
    # Temporary workaround to have discretize wheels built.
    - requirements: .rtd-requirements.txt
    - requirements: requirements-dev.txt
    - method: pip
      path: .
