name: emg3d-gallery

channels:
  - conda-forge

dependencies:
  - "libblas=*=*mkl"
  - empymod
  - emg3d
  - xarray
  - discretize
  - h5py
  - matplotlib
  - scooby
  - sphinx
  - sphinx-gallery
  - numpydoc
  - pooch
  - sphinx_panels
  - pydata-sphinx-theme
  - sphinx_numfig
  - sphinx_automodapi
  - mkl-service
  - tqdm
  - pip
  - pip:
    - setuptools_scm
    - ipykernel
    - memory_profiler
    - asv
    - pytest
    - coveralls
    - pytest-cov
    - pytest-flake8
    - pytest-console-scripts
