name: linux

on:
  push:
    branches:
      - testing

defaults:
  run:
    shell: bash

jobs:
  test:

    name: testing
    runs-on: ubuntu-latest

    steps:

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.11"
          miniforge-version: "latest"
          miniforge-variant: Mambaforge
          use-mamba: true

      - name: Conda settings
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda config --show-sources
          conda config --show
          conda info -a

      - name: Install pyGIMLi
        shell: bash -l {0}
        run: conda install -c gimli -c conda-forge pygimli

      - name: Conda list
        shell: bash -l {0}
        run: conda list

      - name: Which Python
        shell: bash -l {0}
        run: which python

      - name: Import pyGIMLi
        shell: bash -l {0}
        run: python -c 'import pygimli; print(pygimli.Report())'
